### ISSUE TITLE
YouTube error

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#202]
At http://www.wandelenvoorwater.nl/media/video/ there seems to be an error with the integrated YouTube Channel. Does the plugin need to be upgraded maybe?

**Comment by rumeshkumar** [comment]
I will check on this issue and get back to you as soon as possible.

On 21 April 2015 at 13:28, lauraroverts <notifications@github.com> wrote:

> Assigned #202 <https://github.com/akvo/akvo-sites/issues/202> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/202#event-285931565>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
Could you please create a playlist with all the videos and send me the
Playlist ID? The current plugin does not work with the current setup due to
YouTube update. So I will change the settings using playlist ID and try to
make it work.

You can get the playlist ID as follows :-

Go to My Channel => Videos => Select "All Videos" from the "Uploads"
dropdown => Mouse over the "Uploads" title to see a "Play" icon => Click on
the "Play" icon to play first video.

Now, you will see a URL in address bar in the following format

https://www.youtube.com/watch?v=CXa_Ha9dIQA&list=UUV9nsh2GbI5bxdA1gZJ8Q6A

The highlighted one is the Playlist ID.


On 21 April 2015 at 18:42, Rumeshkumar Navaratnam <rumesh@webgurus.lk>
wrote:

> I will check on this issue and get back to you as soon as possible.
>
> On 21 April 2015 at 13:28, lauraroverts <notifications@github.com> wrote:
>
>> Assigned #202 <https://github.com/akvo/akvo-sites/issues/202> to
>> @rumeshkumar <https://github.com/rumeshkumar>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akvo/akvo-sites/issues/202#event-285931565>.
>>
>
>
>
> --
> Regards,
> N Rumeshkumar
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
I think it should be: 
https://www.youtube.com/watch?v=bVwHy8D0qE8&list=UUzzt85MtSWR6jVOJnurMsaw

**Comment by rumeshkumar** [comment]
The YouTube video issue is fixed on Video page and home page. Please make
sure that all the new videos are added under same playlist (ID :
UUzzt85MtSWR6jVOJnurMsaw
<https://www.youtube.com/watch?v=bVwHy8D0qE8&list=UUzzt85MtSWR6jVOJnurMsaw>)
because I am using only this playlist ID to fetch videos.

On 29 April 2015 at 14:38, lauraroverts <notifications@github.com> wrote:

> I think it should be:
> https://www.youtube.com/watch?v=bVwHy8D0qE8&list=UUzzt85MtSWR6jVOJnurMsaw
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/202#issuecomment-97361298>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
thanks a lot!
