### ISSUE TITLE
RSR updates not aligned

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#204]
At the homepage http://www.washalliance.nl the RSR updates are not shown aligned anymore, see screenshot. I might have something to do with this update without an image: http://washalliance.akvoapp.org/project/386/update/9484/. But previously updates without image, automatically showed the country map as featured image instead. 
![screen shot 2015-05-13 at 15 16 16](https://cloud.githubusercontent.com/assets/4179989/7611237/7525e404-f983-11e4-9f38-12a8220b4033.png)

**Comment by rumeshkumar** [comment]
I will check this issue as soon as possible.

On 13 May 2015 at 18:51, lauraroverts <notifications@github.com> wrote:

> Assigned #204 <https://github.com/akvo/akvo-sites/issues/204> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/204#event-303851346>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
In addition: It looks like at http://srhralliance.org automatically an image is added to RSR updates without a picture. But this image somehow comes from http://marsfarmersfirst.com..

See screenshot. Image of cocoa beans
![screen shot 2015-05-20 at 11 55 02](https://cloud.githubusercontent.com/assets/4179989/7723213/421cc398-fee7-11e4-8dbc-c704ac41d118.png)

**Comment by rumeshkumar** [comment]
The issue in http://www.washalliance.nl happens due the API changes in Akvo
APP. When there is no image, it automatically checks for country of the
project and display respected county map as placeholder image. But, the
location(country) table in the database is empty due to Akvo App changes,
It does not display anything.

I have updated the code so that if there is no "project update image" and
"country map", a common place holder image will be displayed.

=================

The issue in http://srhralliance.org also related to placeholder image and
fixed now.

On 20 May 2015 at 15:26, lauraroverts <notifications@github.com> wrote:

> In addition: It looks like at http://srhralliance.org automatically an
> image is added to RSR updates without a picture. But this image somehow
> comes from http://marsfarmersfirst.com..
>
> See screenshot. Image of cocoa beans
> [image: screen shot 2015-05-20 at 11 55 02]
> <https://cloud.githubusercontent.com/assets/4179989/7723213/421cc398-fee7-11e4-8dbc-c704ac41d118.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/204#issuecomment-103830957>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542
