### ISSUE TITLE
Google map disappeared

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#207]
At http://www.gnwp.nl/contact/ the partner accidentely removed the google map, because they wanted to add a picture. Could you get it back again with the following project location? 

https://www.google.nl/maps/place/Nii+Kwabena+Bonnie+Cres,+Accra,+Ghana/@5.6156815,-0.2011778,17z/data=!4m2!3m1!1s0xfdf9bb0b60cf2e5:0x4a27c4d214ba9ff9
Dzorwulu, Accra (No. 122, Nii Bonnie), Ghana.

**Comment by rumeshkumar** [comment]
I have added back the Google map. Please check it and let me know your feedback.

**Comment by rumeshkumar** [comment]
Dear Laura,

This issue is fixed. Please check it and let me know your feedback.

On 28 May 2015 at 15:26, lauraroverts <notifications@github.com> wrote:

> Assigned #207 <https://github.com/akvo/akvo-sites/issues/207> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/207#event-315825559>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
Perfect. Thank you very much!
